### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [mswart/debler#1]
Hi: what would be the license for this repo?
In particular the yarn parser that I could use in the Apache-licensed https://github.com/nexB/scancode-toolkit 
Thanks!
https://github.com/mswart/debler/blob/c3ff2165d155ff3c10446d8f4de62ebc922094c7/debler/yarn/lock.py

**Comment by mswart** [comment]
The project never left the prototype status. It is practical a dead/forgotten project as I will probably never continue this work (although I find the idea still good). But if part of the code is built upon is a nice surprise.

I didn't think about licence until now. I would probably go with GNU LGPLv3.
If this satisfies your need, I will commit a proper licence info.

**Comment by pombredanne** [comment]
@mswart you wrote:

> I didn't think about licence until now. I would probably go with GNU LGPLv3.
> If this satisfies your need, I will commit a proper licence info.

That would be just fine! Thank you ++ for taking the time to reply
